### ISSUE TITLE
[feature request] please support basilisk browser

### ISSUE THREAD

**Issue by hosxy** [Lootyhoof/photonic#2]
Basilisk browser is a new production by palemoon project, could you please consider to support it?

![3260364f-3299-47d4-855a-4b62107faa52](https://user-images.githubusercontent.com/17108640/53681745-d9964180-3d28-11e9-8c97-cb1c0f1a3c44.png)

**Comment by Lootyhoof** [comment]
It's something I've actually been working on for a little while. I can't give any sort of ETA though.

Watch this space..

![Preview](https://i.imgur.com/WFL25f4.png)

**Comment by Lootyhoof** [comment]
http://addons.basilisk-browser.org/addon/photonic/

**Comment by hosxy** [comment]
@Lootyhoof Thank You !!!!!!
