### ISSUE TITLE
reader mode

### ISSUE THREAD

**Issue by rn2208** [Lootyhoof/photonic#5]
After the update, the buttons for changing the text size in the reading mode stopped working. At first I decided that this was a problem with the addon and turned to the author, but he explained that the matter was in themes.
https://github.com/Ascrod/readerview/issues/41#issuecomment-515486368
Please fix this, I really like your theme, but since I often use the reader mode, I have to use the standard one.

**Comment by Lootyhoof** [comment]
This was already fixed in https://github.com/Lootyhoof/photonic/commit/3ecce5499128423fbd0e12c062df345f39f81eb7. I'll be updating it soon.

**Comment by rn2208** [comment]
Star to you. Thanks.
